### ISSUE TITLE
Crash on MacOS with Silicone m1

### ISSUE THREAD

**Issue by paines** [DescentDevelopers/Descent3#126] opened 2024-04-21 06:59 UTC
Compilation works fine with the mac preset. I used the Steam Version to drop in the binary. When the binary is dropped in and started via Steam nothing happens.  I opened a terminal and went to: 
/Users/al/Library/Application Support/Steam/steamapps/common/Descent 3/Descent 3.app/Contents/MacOS and started the binary from there:

./descent3
2024-04-21 08:46:45.429 descent3[31427:27623466] INFO: This app is looking for CD-ROM drives, but no path was specified
2024-04-21 08:46:45.430 descent3[31427:27623466] INFO: Set the SDL12COMPAT_FAKE_CDROM_PATH environment variable to a directory
2024-04-21 08:46:45.430 descent3[31427:27623466] INFO: of MP3 files named trackXX.mp3 where XX is a track number in two digits
2024-04-21 08:46:45.430 descent3[31427:27623466] INFO: from 01 to 99

Descent 3 Linux Client v1.5.0
Copyright (C) 1999 Outrage Entertainment, Inc.

Error: Unable to set temporary directory to: "/Users/al/Library/Application Support/Steam/steamapps/common/Descent 3/Descent 3.app/Contents/MacOS/custom/cache"(Descent 3 Error)

System Error

Press OK to exit, CANCEL to ignore this error and continue.
SIGNAL 5 caught, aborting....

I figured maybe it cannot find the data and so I went to the Resources directory of the package and dropped the binary in there.
When I start descent3 now via Terminal in the Resources directory, the game starts for a few seconds till the dialog where you name the pilot appears, the cursor blinks, and it crashes with a Signal11. Again it shows the INFO about the missing MP3 tracks in the terminal.

starting via lldb shows:

2024-04-21 08:57:26.573998+0200 descent3[31736:27632222] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600000c94800> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2024-04-21 08:57:26.712704+0200 descent3[31736:27632222] [default] CGSWindowShmemCreateWithPort failed on port 0
2024-04-21 08:57:26.712737+0200 descent3[31736:27632222] [default] CGSWindowShmemCreateWithPort failed on port 0
Process 31736 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x550fb23f4)
    frame #0: 0x0000000100261218 descent3`(anonymous namespace)::InternalAudioDecoder::UnpackLinear(decoder=0x0000600003e827f0, id=9, col=0, atEOF=0x000000016fdf817f) at libacm.cpp:585:19
   582 	      return false;
   583 	
   584 	    const uint32 pos = (i << level) + col;
-> 585 	    pBlock[pos] = decoder.m_pMidBuffer[offset - middleIndex];
   586 	  }
   587 	
   588 	  return true;
Target 0: (descent3) stopped.

**Comment by MaddTheSane** [comment] 2024-04-21 07:09
Duplicate of #83.

**Comment by paines** [comment] 2024-04-21 07:14
@MaddTheSane Thanks. I searched the issues for macos but did not see that bug report.

**Closed** 2024-04-21 09:00 UTC
Labels: duplicate
