### ISSUE TITLE
[Runtime Issue]: Missing objects due to upper case HOG file names

### ISSUE THREAD

**Issue by phlash** [DescentDevelopers/Descent3#290] opened 2024-05-06 10:56 UTC
### Build Version

0e69bf465fc6f7bdbf70f46d3a4d4cf1593bc2f6

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Game Environment

Linux 64-bit build on Debian stable (12.5), but issue likely on all case-sensitive file systems where original game content contains upper case file names.

### Description

After recent changes ([commit f7b19d0bf4f0315ba0e6f6ce1e3db58932b05d8e - Fix mercenary features](https://github.com/DescentDevelopers/Descent3/commit/f7b19d0bf4f0315ba0e6f6ce1e3db58932b05d8e)) my local build failed to reach the first menu screen due to a missing object `GuideBotRed` that was referenced in the above commit.

On investigation I discovered that this object exists in the `EXTRA1.HOG` and `EXTRA.HOG` files in my GOG-supplied original content, but these HOGs were not being loaded due to their upper case file names.

Renaming the files (see my updated discussion: https://github.com/DescentDevelopers/Descent3/discussions/93) fixes the problem, _however_ I wonder if it would be prudent to support case-insensitive loading in the `cfile` module?

### Regression Status

Issue not present: ad78f4d7562f615fee1eef59d7a4902c5191b41b
Issue present: f7b19d0bf4f0315ba0e6f6ce1e3db58932b05d8e

### Steps to Reproduce

Issue occurs when loading the game, if both `EXTRA?.HOG` files have any uppercase characters in their name, preventing them from loading.

**Comment by winterheart** [comment] 2024-05-06 10:59
Related to #262.

**Comment by JeodC** [comment] 2024-05-06 11:11
We have two options here: disable the red guidebot if not found (so the game loads), or add case insensitivity, which is what we *should* do. The former is a band-aid, the latter is the solution.

Here's what happened: the red guidebot was outright disabled on linux and mac. You wouldn't have seen it even if extra.hog and extra1.hog were loaded correctly. But, since the engine wasn't case-insensitive anyway, the digital releases would end up doing two things:

- In steam, `extra.hog` would load in place of `extra1.hog`, so the game would be missing the patches in `extra1.hog`.
- In GOG, neither `EXTRA1.HOG` OR `EXTRA.HOG` would be loaded. Mercenary missions were probably unplayable, and if they were playable, they were likely broken.

**Comment by JeodC** [comment] 2024-05-06 12:43
For neatness I'm going to close this as a duplicate of #262

**Closed by JeodC** 2024-05-06 12:43 UTC
Labels: bug
